[project] 
name = "gpha-climb-sars-cov2-lineage-line-list"
version = "3.1.0"
description = "Create Covid lineage line list."
authors = [{name = "Mike Brown", email = "michael.d.brown@ukhsa.gov.uk"}]
requires-python = ">=3.12"
dependencies = ["pandas>=3", "pyyaml", "python-dateutil", "requests", "pango-aliasor"]

[project.optional-dependencies] 
dev = ["ruff", "pytest", "pre-commit"] 

[build-system] 
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts] 
run_linelist = "covid_linelist.run_linelist:main"
get_data_covid_linelist = "covid_linelist.get_data:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"covid_linelist.lib" = ["*.yaml"]

[tool.ruff.lint] 
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # comprehesnions
    "C4",
    # pathlib
    "PTH",
]

ignore = ["E501"] 

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
